### ISSUE TITLE
other binus email domain can't login

### ISSUE THREAD

**Issue by SuperPenguin** [directdevmain/Portal#3]
sadly my batch (17) use @binusian.org instead of @binus.ac.id
maybe the user should enter the email domain manually?
I tried changing @binusian.org and it works so far for me

edit: it's possible to login with id number (for me), so I think it's better to let the user input username manually.

**Comment by chrsep** [comment]
Wow, last time i tried a few months ago it wasn't possible, i'll update it. Are you from kemanggisan campus ?

**Comment by chrsep** [comment]
Done, a77aeb0. I'll publish this to play right away

**Comment by SuperPenguin** [comment]
I'm from jwc campus. Login is now working properly for both email and id.
